import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { NavBar } from "../components/navBar";
import { useResize } from "../hooks/useResize";
import { Footer } from "../sections/Footer";
import { GridAlternateSection } from "../sections/GridAlternateSection";
import { HeroSection } from "../sections/HeroSection";
import { SocialMediaSection } from "../sections/SocialMediaSection";
import styles from "../styles/Home.module.css";
import homeStyled from "../styles/styles";
import { DEFAULT_THEME } from "../themes";
import { applyTheme } from "../themes/utils";

const Home: NextPage = () => {
  const [theme] = useState(DEFAULT_THEME);
  const size = useResize();
  useEffect(() => {
    applyTheme(theme);
  }, [theme]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat:100"
          rel="stylesheet"
        />
      </Head>

      <main>
        <HeroSection breackPoint={size} />
      </main>
      <GridAlternateSection />
      <SocialMediaSection />
      <Footer />
    </div>
  );
};

export default Home;
